### ISSUE TITLE
Clarification Suggestion on Prevalent Space Symbol for Ethiopic

### ISSUE THREAD

**Issue by dyacob** [w3c/typography#2]
In section [3.3.2.5](http://w3c.github.io/typography/#justification_ethi), the statement: "...although modern documents sometimes use a regular space..." implies that "regular space" would be less common than Ethiopic wordspace in modern practices -which is _not_ the case. Regular space is the prevalent separator for most classes of literature since at least the 1960s if not earlier.  Rephrasing suggestions:

"...although modern documents will predominantly use a regular space..."

"...although modern documents will most often use a regular space..."

"...although modern documents will generally use a regular space..."

**Comment by r12a** [comment]
@fantasai this is your text. Let me know what you'd like to do.

**Comment by fantasai** [comment]
Happy to accept the fix. :) All of the background text was thrown together off the top of my head on a plane flight, so inaccuracies like this are somewhat likely.

**Comment by fantasai** [comment]
Among the wording options, I'd go with "usually". "predominantly" can imply that, say, 80% of word separators are regular spaces and the other 20% are Ethiopic.

**Comment by r12a** [comment]
fixed as part of https://github.com/w3c/i18n-drafts/commit/881d7cea66a8ddc70b55b15af76fae518a597fa4
